package community.mitmachim.nativeapp

import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test
import java.io.IOException

class SafetyTest {
 @Test fun donationShortcutUsesActualSitePage(){assertEquals(Route("browser",query="https://mitmachim.top/donation"),categoryShortcut(Category(85,0,"support",3,link="https://mitmachim.top/donation")))}
 @Test fun categoryClickResolvesWithoutLoadedDirectory(){assertEquals(Route("post",pid=427),categoryShortcut(Category(31,0,"welcome",1,link="/post/427")));assertEquals(106,routeFromLink("/topic/106/ברוכים-הבאים")?.tid);assertEquals(5,routeFromLink("/topic/106/welcome/5")?.index)}
 @Test fun compactChatRowsKeepLargeTextAccessible(){assertTrue(compactChatRows(320,640,1f));assertTrue(compactChatRows(400,640,1f));assertFalse(compactChatRows(400,800,1f));assertFalse(compactChatRows(320,640,1.5f))}
 @Test fun categoryShortcutOpensItsForumPost(){val target=resolveCategoryShortcut(Route("category",cid=31),listOf(Category(31,0,"welcome",1,link="https://mitmachim.top/post/427")));assertEquals("post",target.kind);assertEquals(427,target.pid)}
 @Test fun categoryShortcutRejectsExternalLinksAndLoops(){val original=Route("category",cid=31);assertEquals(original,resolveCategoryShortcut(original,listOf(Category(31,0,"welcome",1,link="https://example.com/post/427"))));assertEquals(original,resolveCategoryShortcut(original,listOf(Category(31,0,"a",1,link="/category/32"),Category(32,0,"b",1,link="/category/31"))))}
 @Test fun boundaryNavigationJumpsAcrossAllPages(){val r=Route("topic",tid=42,page=4);val bottom=threadBoundary(r,141,true);assertEquals(141,bottom.page);assertTrue(bottom.end);assertEquals(42,bottom.tid);val top=threadBoundary(bottom,141,false);assertEquals(1,top.page);assertFalse(top.end);assertEquals(1,threadBoundary(r,0,true).page)}
 @Test fun loginRequiresPositiveServerUserId(){try{authenticatedAccount(JSONObject("""{"uid":0,"username":"not signed in"}"""));fail("Guest accepted")}catch(_:IllegalArgumentException){};val a=authenticatedAccount(JSONObject("""{"uid":42,"username":"Tester","userslug":"tester"}"""));assertEquals(42,a.uid);assertEquals("Tester",a.name);assertEquals("tester",a.slug)}
 @Test fun readsBothNotificationBucketsWithoutDuplicates(){val d=JSONObject("""{"unread":[{"nid":"new","bodyShort":"new","datetime":2,"read":0}],"read":[{"nid":"old","bodyShort":"old","datetime":1,"read":1}],"notifications":[{"nid":"new","bodyShort":"new","datetime":2}]}""");val n=parseNotices(d);assertEquals(2,n.size);assertEquals("new",n.first().id);assertFalse(n.first().read);assertTrue(n.last().read)}
 @Test fun parsesRealChatResponseShapes(){val rooms=parseRooms(JSONObject("""{"rooms":[{"roomId":12,"roomName":"Room","unread":1,"teaser":{"content":"<b>hello</b>"}}]}"""));assertEquals(12,rooms.single().id);assertTrue(rooms.single().unread);assertEquals("hello",rooms.single().teaser);val messages=parseMessages(org.json.JSONArray("""[{"mid":3,"timestamp":20,"content":"B","deleted":1},{"messageId":2,"timestamp":10,"content":"A"}]"""));assertEquals(listOf(2,3),messages.map{it.id});assertTrue(messages.last().deleted)}
 @Test fun refusesUnknownChatShapeRatherThanPretendEmpty(){try{parseRooms(JSONObject("""{"unexpected":true}"""));fail("Unknown chat response hidden")}catch(_:IllegalArgumentException){}}
 @Test fun attachmentLinksEscapeNamesAndRejectUnsafeSchemes(){val s=attachmentMarkdown("test[bad].png","image/png","/assets/uploads/test.png");assertTrue(s.startsWith("![test_bad_.png](<https://mitmachim.top/"));try{attachmentMarkdown("file","application/pdf","javascript:alert(1)");fail("Unsafe URL")}catch(_:IllegalArgumentException){}}
 @Test fun nativeIconsInitialize(){assertEquals(24f,AppIcons.Forum.viewportWidth);assertEquals("safety",AppIcons.Shield.name)}
 @Test fun preservesMixedPostDocumentOrder(){val blocks=orderedPostFragments("<div><p>before</p><pre>code</pre><p>between<img src='/assets/a.png'>after</p><table><tr><td>end</td></tr></table></div>");assertEquals(6,blocks.size);assertTrue(blocks[0].contains("before"));assertTrue(blocks[1].startsWith("<pre>"));assertTrue(blocks[2].contains("between"));assertTrue(blocks[3].startsWith("<img"));assertTrue(blocks[4].contains("after"));assertTrue(blocks[5].startsWith("<table>"))}
 @Test fun rejectsForeignOriginsBeforeOpeningConnection(){val client=OkHttpClient.Builder().addInterceptor(ForumOriginGuard()).build();for(url in listOf("https://example.com/","http://mitmachim.top/","https://mitmachim.top:8443/")){try{client.newCall(Request.Builder().url(url).build()).execute();fail("Foreign origin allowed")}catch(_:IOException){}}}
 @Test fun demoBlocksEvenTheForum(){RuntimeSafety.offlineDemo=true;try{val client=OkHttpClient.Builder().addInterceptor(ForumOriginGuard()).build();try{client.newCall(Request.Builder().url("https://mitmachim.top/api/categories").build()).execute();fail("Demo used network")}catch(e:IOException){assertTrue(e.message.orEmpty().contains("דמה"))}}finally{RuntimeSafety.offlineDemo=false}}
 @Test fun rejectsUnsafeLinks(){assertNull(safeLink("javascript:alert(1)"));assertNull(safeLink("http://example.com"));assertNull(safeLink("https://user:password@example.com"));assertEquals("mitmachim.top",safeLink("/topic/95167")?.host)}
 @Test fun preservesPaginationRelatedIdentity(){val t=topic(JSONObject("""{"tid":91,"cid":17,"title":"A &amp; B","postcount":2001,"viewcount":99,"category":{"name":"קטגוריה"}}"""));assertEquals(91,t.id);assertEquals(2001,t.posts);assertEquals("A & B",t.title)}
 @Test fun readsForumAvatarPermissionsAndVoteDirection(){val p=post(JSONObject("""{"pid":37,"index":4,"uid":8,"content":"פוסט","upvotes":1,"downvotes":2,"downvoted":true,"display_edit_tools":true,"display_delete_tools":true,"user":{"displayname":"דוגמה","userslug":"example","picture":"/assets/uploads/avatar.png"}}"""));assertEquals("https://mitmachim.top/assets/uploads/avatar.png",p.avatar);assertEquals("example",p.authorSlug);assertEquals(-1,p.votes);assertTrue(p.downvoted);assertTrue(p.canEdit);assertTrue(p.canDelete);assertEquals("",avatarUrl("javascript:alert(1)"))}
 @Test fun showsSpecificForumRejectionReason(){assertTrue(serverError(403,"""{"status":{"message":"[[error:topic-locked]]"}}""").contains("נעול"));assertTrue(serverError(403,"""{"status":{"message":"[[error:vote-self-post]]"}}""").contains("בעצמך"));assertEquals("אין אפשרות לערוך את הפוסט הזה",serverError(403,"""{"status":{"message":"אין אפשרות לערוך את הפוסט הזה"}}"""))}
 @Test fun opensForumUserLinksInsideApp(){assertEquals("example",routeFromLink("https://mitmachim.top/user/example")?.query);assertNull(routeFromLink("https://example.com/user/example"))}
 @Test fun flattensAllDescendantsAndDeduplicates(){val child=Category(2,1,"child",1);val root=Category(1,0,"root",2,listOf(child,child.copy(children=listOf(Category(3,2,"deep",1)))));assertEquals(listOf(1,2,3),flatten(listOf(root)).map{it.id})}
 @Test fun stripsExecutableHtmlWithoutTruncatingContent(){val d=splitContent("<p>Hello <b>world</b></p><script>alert(1)</script><iframe src='https://example.com'></iframe><img src='javascript:alert(1)'><pre>x&lt;y</pre><table><tr><td>A</td></tr></table>");assertFalse(d.html.contains("script"));assertFalse(d.html.contains("iframe"));assertTrue(d.images.isEmpty());assertTrue(d.html.contains("world"));assertEquals("x<y",d.code.single());assertEquals("A",d.tables.single().single().single())}
 @Test fun markdownEscapesEmbeddedHtml(){val html=markdownToHtml("**bold**\n<script>alert(1)</script>");assertTrue(html.contains("<strong>bold</strong>"));assertFalse(html.contains("<script>"))}
 @Test fun validatesEmptyTitleCategoryAndOversize(){assertNotNull(DraftRules.validate("short","body",17,false));assertNotNull(DraftRules.validate("כותרת ארוכה לדוגמה","",17,false));assertNotNull(DraftRules.validate("כותרת ארוכה לדוגמה","body",0,false));assertNull(DraftRules.validate("","תגובה",0,true));assertNotNull(DraftRules.validate("","123456",0,true,maxPost=5))}
}
